import { Show, createSignal } from "solid-js";

import { AvatarProps } from "../avatar.utils";
import { generateColors, SIZE } from "./avatar-pixel.utils";

function AvatarPixel(props) {
  function pixelColors() {
    return generateColors(props.name, props.colors);
  }

  return (
    <svg
      fill="none"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox={"0 0 " + SIZE + " " + SIZE}
      width={props.size}
      height={props.size}
    >
      <Show when={props.title}>
        <title>{props.name}</title>
      </Show>
      <mask
        id="mask__pixel"
        mask-type="alpha"
        maskUnits="userSpaceOnUse"
        x={0}
        y={0}
        width={SIZE}
        height={SIZE}
      >
        <rect
          fill="#FFFFFF"
          width={SIZE}
          height={SIZE}
          rx={props.square ? undefined : SIZE * 2}
        ></rect>
      </mask>
      <g mask="url(#mask__pixel)">
        <rect width={10} height={10} fill={pixelColors()[0]}></rect>
        <rect x={20} width={10} height={10} fill={pixelColors()[1]}></rect>
        <rect x={40} width={10} height={10} fill={pixelColors()[2]}></rect>
        <rect x={60} width={10} height={10} fill={pixelColors()[3]}></rect>
        <rect x={10} width={10} height={10} fill={pixelColors()[4]}></rect>
        <rect x={30} width={10} height={10} fill={pixelColors()[5]}></rect>
        <rect x={50} width={10} height={10} fill={pixelColors()[6]}></rect>
        <rect x={70} width={10} height={10} fill={pixelColors()[7]}></rect>
        <rect y={10} width={10} height={10} fill={pixelColors()[8]}></rect>
        <rect y={20} width={10} height={10} fill={pixelColors()[9]}></rect>
        <rect y={30} width={10} height={10} fill={pixelColors()[10]}></rect>
        <rect y={40} width={10} height={10} fill={pixelColors()[11]}></rect>
        <rect y={50} width={10} height={10} fill={pixelColors()[12]}></rect>
        <rect y={60} width={10} height={10} fill={pixelColors()[13]}></rect>
        <rect y={70} width={10} height={10} fill={pixelColors()[14]}></rect>
        <rect
          x={20}
          y={10}
          width={10}
          height={10}
          fill={pixelColors()[15]}
        ></rect>
        <rect
          x={20}
          y={20}
          width={10}
          height={10}
          fill={pixelColors()[16]}
        ></rect>
        <rect
          x={20}
          y={30}
          width={10}
          height={10}
          fill={pixelColors()[17]}
        ></rect>
        <rect
          x={20}
          y={40}
          width={10}
          height={10}
          fill={pixelColors()[18]}
        ></rect>
        <rect
          x={20}
          y={50}
          width={10}
          height={10}
          fill={pixelColors()[19]}
        ></rect>
        <rect
          x={20}
          y={60}
          width={10}
          height={10}
          fill={pixelColors()[20]}
        ></rect>
        <rect
          x={20}
          y={70}
          width={10}
          height={10}
          fill={pixelColors()[21]}
        ></rect>
        <rect
          x={40}
          y={10}
          width={10}
          height={10}
          fill={pixelColors()[22]}
        ></rect>
        <rect
          x={40}
          y={20}
          width={10}
          height={10}
          fill={pixelColors()[23]}
        ></rect>
        <rect
          x={40}
          y={30}
          width={10}
          height={10}
          fill={pixelColors()[24]}
        ></rect>
        <rect
          x={40}
          y={40}
          width={10}
          height={10}
          fill={pixelColors()[25]}
        ></rect>
        <rect
          x={40}
          y={50}
          width={10}
          height={10}
          fill={pixelColors()[26]}
        ></rect>
        <rect
          x={40}
          y={60}
          width={10}
          height={10}
          fill={pixelColors()[27]}
        ></rect>
        <rect
          x={40}
          y={70}
          width={10}
          height={10}
          fill={pixelColors()[28]}
        ></rect>
        <rect
          x={60}
          y={10}
          width={10}
          height={10}
          fill={pixelColors()[29]}
        ></rect>
        <rect
          x={60}
          y={20}
          width={10}
          height={10}
          fill={pixelColors()[30]}
        ></rect>
        <rect
          x={60}
          y={30}
          width={10}
          height={10}
          fill={pixelColors()[31]}
        ></rect>
        <rect
          x={60}
          y={40}
          width={10}
          height={10}
          fill={pixelColors()[32]}
        ></rect>
        <rect
          x={60}
          y={50}
          width={10}
          height={10}
          fill={pixelColors()[33]}
        ></rect>
        <rect
          x={60}
          y={60}
          width={10}
          height={10}
          fill={pixelColors()[34]}
        ></rect>
        <rect
          x={60}
          y={70}
          width={10}
          height={10}
          fill={pixelColors()[35]}
        ></rect>
        <rect
          x={10}
          y={10}
          width={10}
          height={10}
          fill={pixelColors()[36]}
        ></rect>
        <rect
          x={10}
          y={20}
          width={10}
          height={10}
          fill={pixelColors()[37]}
        ></rect>
        <rect
          x={10}
          y={30}
          width={10}
          height={10}
          fill={pixelColors()[38]}
        ></rect>
        <rect
          x={10}
          y={40}
          width={10}
          height={10}
          fill={pixelColors()[39]}
        ></rect>
        <rect
          x={10}
          y={50}
          width={10}
          height={10}
          fill={pixelColors()[40]}
        ></rect>
        <rect
          x={10}
          y={60}
          width={10}
          height={10}
          fill={pixelColors()[41]}
        ></rect>
        <rect
          x={10}
          y={70}
          width={10}
          height={10}
          fill={pixelColors()[42]}
        ></rect>
        <rect
          x={30}
          y={10}
          width={10}
          height={10}
          fill={pixelColors()[43]}
        ></rect>
        <rect
          x={30}
          y={20}
          width={10}
          height={10}
          fill={pixelColors()[44]}
        ></rect>
        <rect
          x={30}
          y={30}
          width={10}
          height={10}
          fill={pixelColors()[45]}
        ></rect>
        <rect
          x={30}
          y={40}
          width={10}
          height={10}
          fill={pixelColors()[46]}
        ></rect>
        <rect
          x={30}
          y={50}
          width={10}
          height={10}
          fill={pixelColors()[47]}
        ></rect>
        <rect
          x={30}
          y={60}
          width={10}
          height={10}
          fill={pixelColors()[48]}
        ></rect>
        <rect
          x={30}
          y={70}
          width={10}
          height={10}
          fill={pixelColors()[49]}
        ></rect>
        <rect
          x={50}
          y={10}
          width={10}
          height={10}
          fill={pixelColors()[50]}
        ></rect>
        <rect
          x={50}
          y={20}
          width={10}
          height={10}
          fill={pixelColors()[51]}
        ></rect>
        <rect
          x={50}
          y={30}
          width={10}
          height={10}
          fill={pixelColors()[52]}
        ></rect>
        <rect
          x={50}
          y={40}
          width={10}
          height={10}
          fill={pixelColors()[53]}
        ></rect>
        <rect
          x={50}
          y={50}
          width={10}
          height={10}
          fill={pixelColors()[54]}
        ></rect>
        <rect
          x={50}
          y={60}
          width={10}
          height={10}
          fill={pixelColors()[55]}
        ></rect>
        <rect
          x={50}
          y={70}
          width={10}
          height={10}
          fill={pixelColors()[56]}
        ></rect>
        <rect
          x={70}
          y={10}
          width={10}
          height={10}
          fill={pixelColors()[57]}
        ></rect>
        <rect
          x={70}
          y={20}
          width={10}
          height={10}
          fill={pixelColors()[58]}
        ></rect>
        <rect
          x={70}
          y={30}
          width={10}
          height={10}
          fill={pixelColors()[59]}
        ></rect>
        <rect
          x={70}
          y={40}
          width={10}
          height={10}
          fill={pixelColors()[60]}
        ></rect>
        <rect
          x={70}
          y={50}
          width={10}
          height={10}
          fill={pixelColors()[61]}
        ></rect>
        <rect
          x={70}
          y={60}
          width={10}
          height={10}
          fill={pixelColors()[62]}
        ></rect>
        <rect
          x={70}
          y={70}
          width={10}
          height={10}
          fill={pixelColors()[63]}
        ></rect>
      </g>
    </svg>
  );
}

export default AvatarPixel;
