// GENERATED BY MITOSIS

import { AvatarShape, shapes } from "../utils/common.utils";
import {
  Fragment,
  component$,
  h,
  useClientEffect$,
  useStore,
  useWatch$,
} from "@builder.io/qwik";
import type { ShapeSelectorProps } from "./shape-selector.utils";
export const handleChange = function handleChange(props, state, event: any) {
  props.onChange$(
    ((event?.target as HTMLInputElement)?.value as AvatarShape) ||
      AvatarShape.Circle
  );
};
export const getCircleLabelClass = function getCircleLabelClass(props, state) {
  return `radio-label ${
    AvatarShape.Circle === state.selectedShape ? "selected" : ""
  }`;
};
export const getSquareLabelClass = function getSquareLabelClass(props, state) {
  return `radio-label ${
    AvatarShape.Square === state.selectedShape ? "selected" : ""
  }`;
};
export const ShapeSelector = component$((props: any) => {
  const state = useStore<any>({ selectedShape: AvatarShape.Circle });
  useClientEffect$(() => {
    state.selectedShape = props.shape || AvatarShape.Circle;
  });
  useWatch$(({ track }) => {
    props && track(props, "shape");
    state.selectedShape = props.shape || AvatarShape.Circle;
  });
  return (
    <div class="shape-selector widget-wrapper">
      <label htmlFor="radio-circle" class={getCircleLabelClass(props, state)}>
        <input
          id="radio-circle"
          type="radio"
          class="sr-only radio-item"
          value="circle"
          name="shape-option"
          onChange$={(event) => handleChange(props, state, event)}
        ></input>
        <svg width="13" height="13" fill="none">
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M7.07 6.837C6.242 7.603 5.5 9.187 5.5 13h-5c0-4.187.759-7.603 3.18-9.837C6.05.973 9.415.5 13 .5v5c-3.416 0-5.051.527-5.93 1.337z"
            fill="currentColor"
          ></path>
        </svg>
      </label>
      <label htmlFor="radio-square" class={getSquareLabelClass(props, state)}>
        <input
          id="radio-square"
          type="radio"
          class="sr-only radio-item"
          value="square"
          name="shape-option"
          onChange$={(event) => handleChange(props, state, event)}
        ></input>
        <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M0.5 0.5H13V5.5H5.5V13H0.5V0.5Z"
            fill="currentColor"
          ></path>
        </svg>
      </label>
    </div>
  );
});
export default ShapeSelector;
