// GENERATED BY MITOSIS

import { SIZE, generateColors } from "./avatar-pixel.utils";
import { Fragment, component$, h } from "@builder.io/qwik";
export const pixelColors = function pixelColors(props, state) {
  return generateColors(props.name, props.colors);
};
export const AvatarPixel = component$((props) => {
  const state = {};
  return (
    <svg
      fill="none"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox={"0 0 " + SIZE + " " + SIZE}
      width={props.size}
      height={props.size}
    >
      {props.title ? <title>{props.name}</title> : null}
      <mask
        id="mask__pixel"
        mask-type="alpha"
        maskUnits="userSpaceOnUse"
        x={0}
        y={0}
        width={SIZE}
        height={SIZE}
      >
        <rect
          fill="#FFFFFF"
          width={SIZE}
          height={SIZE}
          rx={props.square ? undefined : SIZE * 2}
        ></rect>
      </mask>
      <g mask="url(#mask__pixel)">
        <rect width={10} height={10} fill={pixelColors(props, state)[0]}></rect>
        <rect
          x={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[1]}
        ></rect>
        <rect
          x={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[2]}
        ></rect>
        <rect
          x={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[3]}
        ></rect>
        <rect
          x={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[4]}
        ></rect>
        <rect
          x={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[5]}
        ></rect>
        <rect
          x={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[6]}
        ></rect>
        <rect
          x={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[7]}
        ></rect>
        <rect
          y={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[8]}
        ></rect>
        <rect
          y={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[9]}
        ></rect>
        <rect
          y={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[10]}
        ></rect>
        <rect
          y={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[11]}
        ></rect>
        <rect
          y={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[12]}
        ></rect>
        <rect
          y={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[13]}
        ></rect>
        <rect
          y={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[14]}
        ></rect>
        <rect
          x={20}
          y={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[15]}
        ></rect>
        <rect
          x={20}
          y={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[16]}
        ></rect>
        <rect
          x={20}
          y={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[17]}
        ></rect>
        <rect
          x={20}
          y={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[18]}
        ></rect>
        <rect
          x={20}
          y={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[19]}
        ></rect>
        <rect
          x={20}
          y={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[20]}
        ></rect>
        <rect
          x={20}
          y={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[21]}
        ></rect>
        <rect
          x={40}
          y={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[22]}
        ></rect>
        <rect
          x={40}
          y={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[23]}
        ></rect>
        <rect
          x={40}
          y={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[24]}
        ></rect>
        <rect
          x={40}
          y={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[25]}
        ></rect>
        <rect
          x={40}
          y={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[26]}
        ></rect>
        <rect
          x={40}
          y={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[27]}
        ></rect>
        <rect
          x={40}
          y={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[28]}
        ></rect>
        <rect
          x={60}
          y={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[29]}
        ></rect>
        <rect
          x={60}
          y={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[30]}
        ></rect>
        <rect
          x={60}
          y={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[31]}
        ></rect>
        <rect
          x={60}
          y={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[32]}
        ></rect>
        <rect
          x={60}
          y={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[33]}
        ></rect>
        <rect
          x={60}
          y={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[34]}
        ></rect>
        <rect
          x={60}
          y={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[35]}
        ></rect>
        <rect
          x={10}
          y={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[36]}
        ></rect>
        <rect
          x={10}
          y={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[37]}
        ></rect>
        <rect
          x={10}
          y={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[38]}
        ></rect>
        <rect
          x={10}
          y={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[39]}
        ></rect>
        <rect
          x={10}
          y={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[40]}
        ></rect>
        <rect
          x={10}
          y={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[41]}
        ></rect>
        <rect
          x={10}
          y={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[42]}
        ></rect>
        <rect
          x={30}
          y={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[43]}
        ></rect>
        <rect
          x={30}
          y={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[44]}
        ></rect>
        <rect
          x={30}
          y={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[45]}
        ></rect>
        <rect
          x={30}
          y={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[46]}
        ></rect>
        <rect
          x={30}
          y={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[47]}
        ></rect>
        <rect
          x={30}
          y={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[48]}
        ></rect>
        <rect
          x={30}
          y={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[49]}
        ></rect>
        <rect
          x={50}
          y={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[50]}
        ></rect>
        <rect
          x={50}
          y={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[51]}
        ></rect>
        <rect
          x={50}
          y={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[52]}
        ></rect>
        <rect
          x={50}
          y={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[53]}
        ></rect>
        <rect
          x={50}
          y={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[54]}
        ></rect>
        <rect
          x={50}
          y={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[55]}
        ></rect>
        <rect
          x={50}
          y={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[56]}
        ></rect>
        <rect
          x={70}
          y={10}
          width={10}
          height={10}
          fill={pixelColors(props, state)[57]}
        ></rect>
        <rect
          x={70}
          y={20}
          width={10}
          height={10}
          fill={pixelColors(props, state)[58]}
        ></rect>
        <rect
          x={70}
          y={30}
          width={10}
          height={10}
          fill={pixelColors(props, state)[59]}
        ></rect>
        <rect
          x={70}
          y={40}
          width={10}
          height={10}
          fill={pixelColors(props, state)[60]}
        ></rect>
        <rect
          x={70}
          y={50}
          width={10}
          height={10}
          fill={pixelColors(props, state)[61]}
        ></rect>
        <rect
          x={70}
          y={60}
          width={10}
          height={10}
          fill={pixelColors(props, state)[62]}
        ></rect>
        <rect
          x={70}
          y={70}
          width={10}
          height={10}
          fill={pixelColors(props, state)[63]}
        ></rect>
      </g>
    </svg>
  );
});
export default AvatarPixel;
